steps:
  - name: gcr.io/cloud-builders/docker
    args:
    - build
    - -t
    - service-builder
    - -f
    - production/packaging/gcp/cloud_build/Dockerfile
    - .
  - name: service-builder
    env:
      - WORKSPACE_MOUNT=/workspace
    script: |
      #!/usr/bin/env bash
      production/packaging/build_and_test_all_in_docker \
      --service-path buyer_frontend_service \
      --service-path bidding_service \
      --service-path seller_frontend_service \
      --service-path auction_service \
      --instance gcp --platform gcp \
      --build-flavor prod \
      --gcp-image-tag ${_GCP_IMAGE_TAG} \
      --gcp-image-repo ${_GCP_IMAGE_REPO} \
      --no-tests --no-precommit
substitutions:
    _GCP_IMAGE_TAG: from-cloudbuild # Default. The build script also tags the images with verison information.
    _GCP_IMAGE_REPO: us-docker.pkg.dev/$PROJECT_ID/services # Default. Artifact Registry repo to house images for each service.
timeout: 10800s
options:
  machineType: E2_HIGHCPU_32
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
