steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_BUILD_BASE_IMAGE', '-f', 'production/packaging/gcp/cloud_build/Dockerfile', '.']
  - name: '$_BUILD_BASE_IMAGE'
    env:
      - WORKSPACE_MOUNT=/workspace
    script: >
      ./production/packaging/build_and_test_all_in_docker --service-path
      buyer_frontend_service --service-path bidding_service   --service-path
      seller_frontend_service --service-path auction_service  --instance gcp 
      --platform gcp --no-precommit --gcp-image-tag $_GCP_IMAGE_TAG --gcp-image-repo
      $_GCP_IMAGE_REPO --build-flavor prod
      --no-tests
timeout: 10800s
options:
  machineType: E2_HIGHCPU_32
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
