steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - build
    - -t
    - service-builder
    - -f
    - production/packaging/gcp/cloud_build/Dockerfile
    - .
  - name: 'service-builder'
    env:
      - WORKSPACE_MOUNT=/workspace
    script: >
      production/packaging/build_and_test_all_in_docker \
      --service-path buyer_frontend_service \
      --service-path bidding_service \
      --service-path seller_frontend_service \
      --service-path auction_service \
      --instance gcp  --platform gcp \
      --build-flavor prod \
      --gcp-image-tag ${_GCP_IMAGE_TAG} \
      --gcp-image-repo ${_GCP_IMAGE_REPO} \
      --no-tests --no-precommit
timeout: 10800s
options:
  machineType: E2_HIGHCPU_32
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
