version: 0.2

phases:
  build:
    commands:
      - export ROLE_INFO=$(curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI)
      - export AWS_ACCESS_KEY_ID=$(echo $ROLE_INFO | jq -r '.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo $ROLE_INFO | jq -r '.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo $ROLE_INFO | jq -r '.Token')
      - export AWS_DEFAULT_REGION=$AMI_REGION
      - WORKSPACE_MOUNT=${CODEBUILD_SRC_DIR} ./production/packaging/build_and_test_all_in_docker --service-path buyer_frontend_service --service-path bidding_service --service-path seller_frontend_service --service-path auction_service --instance aws --platform aws --no-precommit --with-ami $AMI_REGION --build-flavor prod --no-tests
