name: Sync Fork

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
  workflow_dispatch: # on button click

jobs:
  sync_code:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        continue-on-error: true
        with:
          base: main
          head: main
      - name: Checkout Code
        uses: actions/checkout@v3
        if: always()       # Always checkout, even if sync fails
      - name: Sync Tags with Upstream
        if: always()       # Always sync tags, even if sync or checkout fails
        run: |
          git fetch https://github.com/privacysandbox/bidding-auction-servers --tags --force
          git push origin --tags --force